### ISSUE TITLE
What does this do with forced subtitles?

### ISSUE THREAD

**Issue by MattPark** [binhex/videoslimmer#3]
For instance you have an english audio track and someone speaks french.  Usually there are subtitles there and if you remove ALL of them you would lose the french dialog.

**Comment by binhex** [comment]
i see your point, but if somebody speaks french you would want to see subtitles for your chosen language, in your case english, you wouldnt want to see french subtitles, or am i reading your comment wrong?

**Comment by MattPark** [comment]
Yeah... let's take it a step further.  Forced subtitles are usually used when subtitles are otherwise turned off.  For instance if you are watching a movie in english, and an extraterrestrial speaks, there are often forced subtitles that show what the alien was saying.

In other words, if there is a forced flag on the subtitles, you shoudn't remove them.  They will be small anyway

**Comment by binhex** [comment]
sorry i still dont get it, if you have a movie that has forced subtitles, what language would you want the force subtitles to be in?, the answer is your chosen language, which is what you specify when you run videoslimmer from the cli, videoslimmer will NOT remove any subtitles that are for your chosen language, whether they are force subtitles or not, AND as a safety precaution it wont remove foreign subtitles if subtitles for your chosen language are not found. im going to close this off for now, please feel free to re-open if you think there is another use case that i havent covered here.
