### ISSUE TITLE
Question, how does this handle und (unknown lang tracks)

### ISSUE THREAD

**Issue by jscottdouglas** [binhex/videoslimmer#5]
this is not an issue but just wondering how this handles unknown lang tracks, anyway to set unknown tracks to say eng with this?

**Comment by binhex** [comment]
This script will only remove audio tracks (including unknown audio tracks) **IF** there is a matching preferred audio track, so if no match then no audio tracks are removed. I have yet to see a case where this causes a loss of audio track, even for foreign movies with subtitles, any thoughts on this?.

**Comment by binhex** [comment]
anyway to set unknown tracks to say eng with this? - it COULD do this but how would you identify the language of the unknown track, surely thats impossible?.

**Comment by jscottdouglas** [comment]
I would want to set it because I know that the unknown tracks are English,
alot of TV shows seem to be encoded without setting the Lang to English so
it defaults to unknown
