### ISSUE TITLE
Dockerize this?

### ISSUE THREAD

**Issue by RandomNinjaAtk** [binhex/videoslimmer#8]
I've been attempting to get this to work without much luck, looks to be a mkvtoolnix issue with the version... But this would cool if this was in a docker that could be loaded onto unraid or freenas.

**Comment by gbougiakas** [comment]
I agree 100%. I assume the author is the same person as the one that creates and maintains all those unraid binhex containers.

**Comment by binhex** [comment]
please seem my comment linked above, in short i would prefer to go down the post processing route rathan than crack a nut with a sledge hammer (aka docker).
